### ISSUE TITLE
How I Verify My Custom Domain?

### ISSUE THREAD

**Issue by Huseyin-Cinar** [tarampampam/free-domains#126]

**Comment by Huseyin-Cinar** [comment]
I not know "How I Verify My Custom Domain?" can you help me @tarampampam

**Comment by tarampampam** [comment]
Lol, I have no idea since I have never used Netlify 😆 I can help you to make DNS records or something like that, not more

**Comment by Huseyin-Cinar** [comment]
hey bro in netlify you have https cert this is true but if you not buy a custom domain you can't verify your subdomain.

**Comment by Huseyin-Cinar** [comment]
so i can't making solve to this problem i think this problem have no any solution if you buy a custom domain :(

**Comment by tarampampam** [comment]
Ok, if this is true - feel free to close this issue, I hope that I can help you with something... Sorry
