### ISSUE TITLE
Hosting 

### ISSUE THREAD

**Issue by ElonMusk49** [tarampampam/free-domains#128]
Do you know any Hosting site through which i can upload my webpage on these free subdomain?

Or how to upload my HTML webpage on these free subdomain?

**Comment by BasToTheMax** [comment]
You could use github pages (free)

**Comment by tarampampam** [comment]
Or ClougFlare

**Comment by tarampampam** [comment]
Or GitLab pages

**Comment by ElonMusk49** [comment]
Ohk Thanks

**Comment by ElonMusk49** [comment]
By the way my pull request has stuck on dns control check .
Did i miss anything to do
