### ISSUE TITLE
DNS Check Unsuccessful 

### ISSUE THREAD

**Issue by DoctorStrange49** [tarampampam/free-domains#136]
![Screenshot_2023-02-26-23-01-05-27_c0dc27f5c07cb0fb3541d6073dfd6932](https://user-images.githubusercontent.com/108475621/221426476-a58caed2-f42a-47f0-896a-2be844fcb3ea.jpg)

**Comment by DoctorStrange49** [comment]
![Screenshot_2023-02-26-23-02-11-87_c0dc27f5c07cb0fb3541d6073dfd6932](https://user-images.githubusercontent.com/108475621/221426514-6da120b9-efab-43c0-8ffa-d5f6b678f74c.jpg)

**Comment by DoctorStrange49** [comment]
Sir ?
@tarampampam

**Comment by DoctorStrange49** [comment]
Bro ?
@tarampampam

**Comment by tarampampam** [comment]
Try to remove `www.`

**Comment by tarampampam** [comment]
Closed due inactivity
