### ISSUE TITLE
something happened

### ISSUE THREAD

**Issue by Ben569483** [tarampampam/free-domains#199]
so something happened with my host and now it says my site https://bengames.is-an.app isn't CNAME pointed to my site even though it is, not sure if this is an issue with the host or the is-an.app domain

![image](https://user-images.githubusercontent.com/35010334/224171773-a587d359-bf5a-4c57-bccf-91d1385faf8f.png)

**Comment by tarampampam** [comment]
The record exists and resolving works fine:

https://github.com/tarampampam/free-domains/blob/eac976cae054a37fe41d9068c4db24bb71c842e1/domains/bengames.is-an.app.js#L9-L11

```bash
dig bengames.is-an.app

; <<>> DiG 9.16.1-Ubuntu <<>> bengames.is-an.app
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35304
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;bengames.is-an.app.		IN	A

;; ANSWER SECTION:
bengames.is-an.app.	300	IN	A	172.67.181.22
bengames.is-an.app.	300	IN	A	104.21.64.101

;; Query time: 92 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Fri Mar 10 14:34:20 +04 2023
;; MSG SIZE  rcvd: 79
```

I have no idea what happened, sorry
