### ISSUE TITLE
Netlify support

### ISSUE THREAD

**Issue by ludg1e** [tarampampam/free-domains#314]
Hello, i'd like to know if it works if I add a subdomain into Netlify domains management of my page.
Thank you

**Comment by tarampampam** [comment]
Is it enough?

https://github.com/tarampampam/free-domains/blob/fb640e31af50f017b7939d3aca4e148e8d903861/README.md?plain=1#L125-L127

**Comment by tarampampam** [comment]
What the Netlify requires for that?

**Comment by ludg1e** [comment]
If I setup, for e.g a 1bt.uk subdomain here as ludgie.1bt.uk, it should work with GitHub pages but for netlify as far as I know you need to add the main domain (1bt.uk) to your team/website deployment domains tab in someway, and that's not possible if I recall.
I don't know if you could dig up into the issue.

More info here:
https://docs.netlify.com/domains-https/custom-domains/

Thank you.
