### ISSUE TITLE
Bring back NS records

### ISSUE THREAD

**Issue by ririko5834** [tarampampam/free-domains#360]
Bring back NS records support please

**Comment by ririko5834** [comment]
![image](https://github.com/tarampampam/free-domains/assets/64729293/b56022f6-bc70-4ec0-8afc-c30a4d380230)

**Comment by ririko5834** [comment]
from https://github.com/js-org/js.org/wiki/Similar-Services

**Comment by tarampampam** [comment]
https://github.com/tarampampam/free-domains/blob/7da7a9aa0633cd1756341f6f3daf758f1e8b3e13/README.md?plain=1#L96
https://github.com/tarampampam/free-domains/blob/7da7a9aa0633cd1756341f6f3daf758f1e8b3e13/README.md?plain=1#L21-L22
