### ISSUE TITLE
Domains cleanup

### ISSUE THREAD

**Issue by tarampampam** [tarampampam/free-domains#47]
The following subdomain will be removed soon:

- `waifu.is-an.app` (SSL handshake failed) @Oreki-Dev 
- ~~`survival2d.is-an.app` (CNAME Cross-User Banned)~~ @tiennm99
- `rwbox.is-an.app` (There isn't a GitHub Pages site here) @ourstorycomic 
- `gamingella.is-an.app` (There isn't a GitHub Pages site here) @rhysjamesmason 
- `cosmo.is-an.app` (Placeholder) @valhk
- ~~`bengames.is-an.app` (NET::ERR_CERT_COMMON_NAME_INVALID)~~ @Ben569483
- `aniruddh.is-an.app` (Placeholder) @aniruddhnishad

**Comment by Ben569483** [comment]
oh yeah my host doesn't give SSL certificates to free users, if i find another host that gives an SSL certificate can i make another pull request?

**Comment by tarampampam** [comment]
@Ben569483 Yes, sure! Or we could try to enable a CF proxy for your domain. Could this solve the problem?

**Comment by Ben569483** [comment]
Yeah we can try that, if it doesn't work I'll look for a host that has SSL

**Comment by tarampampam** [comment]
@Ben569483 

![image](https://user-images.githubusercontent.com/7326800/209582700-d7d6e595-d2a0-4fb2-9006-fa7b32595bf9.png)

Is this ok?

**Comment by Ben569483** [comment]
Yep that's how it should be!

**Comment by tarampampam** [comment]
@Ben569483 Viola! 😄

**Comment by Ben569483** [comment]
Seems like I can't access any folders on the server

**Comment by Ben569483** [comment]
Nevermind, works now

**Comment by tarampampam** [comment]
Glad to hear that!

**Comment by Ben569483** [comment]
Thanks for the help! :)

**Comment by aniruddhnishad** [comment]
why you removing aniruddh.is-an.app? it`s working fine

**Comment by Ben569483** [comment]
> why you removing aniruddh.is-an.app? it`s working fine

it's because your site only has text saying "hello"
