### ISSUE TITLE
How to give away subdomains myself ?

### ISSUE THREAD

**Issue by KaKi87** [tarampampam/free-domains#59]
Hello,

I have a 4-letter FQDN that will serve a free and open source URL shortener.

As a secondary use for it, I'm thinking about giving away subdomains too.

How can I do that ?

Thanks

**Comment by tarampampam** [comment]
Hmm... Technically it depends on the DNS provider. If it has an API - integrate your backend with it and... That's it!

**Comment by KaKi87** [comment]
My DNS provider is OVH and has an API, which is used by acme.sh for example.

Does the repo contain the source code for that integration ?

Aren't you using GitHub Actions to make those requests ?

What about you @is-a-dev, you mentioned your project is based on this one, how did you do it ?

Thanks

**Comment by tarampampam** [comment]
> Does the repo contain the source code for that integration?

Yes, and I have used [dnscontrol](https://github.com/StackExchange/dnscontrol) for this. Watch the repository sources

> Aren't you using GitHub Actions to make those requests?

Actions are used, of course. Watch the repository sources

> What about you https://github.com/is-a-dev, you mentioned your project is based on this one, how did you do it?

Where mentioned?

**Comment by KaKi87** [comment]
My bad, not *based on*, just *related*, from *free-for.dev*.

Considering both are using git PR-based registration, I assumed they shared the same codebase, but it seems not. Sorry :sweat_smile:
