### ISSUE TITLE
Domain doesn't work with Vercel

### ISSUE THREAD

**Issue by ToastifyDev** [tarampampam/free-domains#97]
When I tried to add my domain to my Vercel website, it showed me this error:
![image](https://user-images.githubusercontent.com/50563138/216926574-b08c4bb7-d517-4873-8491-8727af3374e9.png)

**Comment by tarampampam** [comment]
Copy-paste the required record here, please. I will append it manually

**Comment by ToastifyDev** [comment]
```
vc-domain-verify=mercurybot.is-an.app,7b7abce6fa5f6f411705
```

**Comment by tarampampam** [comment]
Not a problem 🤝 Chech now, please?

**Comment by ToastifyDev** [comment]
It's all good. Closing this issue now.
